const assets={btc:{name:'Bitcoin',symbol:'BTC',price:67432.18,change:'+2.45%',icon:'₿'},eth:{name:'Ethereum',symbol:'ETH',price:3248.76,change:'+3.12%',icon:'Ξ'},tsla:{name:'Tesla',symbol:'TSLA',price:248.32,change:'+1.95%',icon:'T'},gold:{name:'Gold',symbol:'XAU',price:2345.60,change:'+0.72%',icon:'Au'},aapl:{name:'Apple',symbol:'AAPL',price:189.24,change:'+1.18%',icon:'A'}}; 
function money(n){return '$'+Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function chart(){let pts=[];for(let i=0;i<34;i++){let y=190-(i*2.1)-Math.sin(i/2)*18-Math.random()*12;pts.push(`${i*3.1},${y}`)}return `<svg viewBox="0 0 105 210" preserveAspectRatio="none"><path d="M0 205 ${pts.map(p=>'L'+p).join(' ')} L105 210 Z" fill="#163d48"/><polyline points="${pts.join(' ')}" fill="none" stroke="#55e0ae" stroke-width="1.5" vector-effect="non-scaling-stroke"/></svg>`}
function renderAssets(){let el=document.getElementById('assetList');if(!el)return;el.innerHTML=Object.entries(assets).map(([id,a])=>`<a class="asset-row" href="asset.html?asset=${id}"><span class="coin">${a.icon}</span><span><b>${a.name}</b><small>${a.symbol} / USD</small></span><strong>${money(a.price)} <i>${a.change}</i></strong></a>`).join('')}
function renderAsset(){let el=document.getElementById('assetDetail');if(!el)return;let id=new URLSearchParams(location.search).get('asset')||'btc',a=assets[id]||assets.btc;el.innerHTML=`<p class="eyebrow">${a.symbol} / USD</p><h1>${a.name} (${a.symbol})</h1><div class="stats"><div><small>Displayed market price</small><b>${money(a.price)}</b></div><div><small>24h movement</small><b style="color:#55e0ae">${a.change}</b></div><div><small>Account balance</small><b>$0.00</b></div><div><small>Data status</small><b>Demo</b></div></div><div class="chart">${chart()}</div><p class="notice">This chart is illustrative demo data. Production deployment must connect a licensed market-data API through a secure backend, display the provider timestamp, and handle disconnections.</p><div class="panel"><h2>About ${a.name}</h2><p>Asset information, risk disclosures, eligibility, fees and execution details must be supplied from verified sources before this product is offered to customers.</p><a class="btn gold" href="register.html">Create account</a></div>`}
function demoLogin(e){e.preventDefault();document.getElementById('authMessage').textContent='Demo login submitted. Connect this form to a secure backend authentication service.'}
function demoRegister(e){e.preventDefault();document.getElementById('authMessage').textContent='Demo account form submitted. Connect this form to secure backend registration and verification.'}
function submitDeposit(e){e.preventDefault();alert('Demo: deposit request recorded as PENDING. No funds were credited.');location.href='dashboard.html'}
function submitWithdrawal(e){e.preventDefault();alert('Demo: withdrawal request recorded as PENDING for admin review.');location.href='dashboard.html'}
renderAssets();renderAsset();